---
title: "Firearm Ownership in California: Results from the 2018 California Safety and Wellbeing Survey (CSaWS)"
output: html_document
---

```{r, include=FALSE}
setwd("/Users/jschleimer1/Documents/VPRP/My Projects/CSaWS/")
library(rgdal)
UPPER <- readOGR(dsn = "/Users/jschleimer1/Documents/VPRP/My Projects/CSaWS/", layer = "UPPER")

LOWER <- readOGR(dsn = "/Users/jschleimer1/Documents/VPRP/My Projects/CSaWS/", layer = "LOWER")


```


## State Senate Districts

```{r, width = 40, height = 30, echo=FALSE}

library(leaflet)

l <- leaflet(UPPER) %>% addTiles()
pal <- colorNumeric(c("YlOrRd"), UPPER$PREV1A)

pal_rev <- colorNumeric(c("YlOrRd"), UPPER$PREV1A, reverse = TRUE)
labels <- sprintf("<strong> %s </strong> <br/> prevalence: %s ",
                  UPPER$NAMELSA, round(UPPER$PREV1A,1)) %>%
  lapply(htmltools::HTML)
l %>% addPolygons(color = "grey", weight = 1, fillColor = ~pal(PREV1A), fillOpacity = 0.5,
                  highlightOptions = highlightOptions(weight = 4), label = labels,
                  labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                           padding = "3px 8px"),
                                              textsize = "15px",
                                              direction = "auto")) %>%
  addLegend(pal = pal_rev, values = ~PREV1A,labFormat = labelFormat(transform = function(PREV1A) 
    sort(PREV1A, decreasing = TRUE)),
    opacity = 0.5, title = "Prevalence (%)",
    position = "topright")

```


## State Assembly Districts

```{r, width = 40, height = 30, echo=FALSE}


library(leaflet)
l <- leaflet(LOWER) %>% addTiles()
pal <- colorNumeric(c("YlOrRd"), LOWER$PREV2)
pal_rev <- colorNumeric(c("YlOrRd"), LOWER$PREV2, reverse = TRUE)
labels <- sprintf("<strong> %s </strong> <br/> prevalence: %s ",
                  LOWER$AssmblD, round(LOWER$PREV2,1)) %>%
  lapply(htmltools::HTML)
l %>% addPolygons(color = "grey", weight = 1, fillColor = ~pal(PREV2), fillOpacity = 0.5,
                  highlightOptions = highlightOptions(weight = 4), label = labels,
                  labelOptions = labelOptions(style = list("font-weight" = "normal",
                                                           padding = "3px 8px"),
                                              textsize = "15px",
                                              direction = "auto")) %>%
  addLegend(pal = pal_rev, values = ~PREV2,labFormat = labelFormat(transform = function(PREV2) 
    sort(PREV2, decreasing = TRUE)),
            opacity = 0.5, title = "Prevalence (%)",
            position = "topright")

```


